logging:
  level:
    com.vpclub.bait.busticket.query: debug

spring:
  rabbitmq:
    host: rabbit-prod

app:
  name: busticket
  project: bait
  role: query
  descriptions: '汽车票查询模块'
  cluster-name: bait
  datasource:
    name: bait_busticket
    username: bait
    password: XbuxY7wmohro1e+SBAMZdQJvRW6FyIacOXA/yiQcP5Eb5GFB+H+mxYw4bkeBW1rVE7b/cokdeXxQFyI3kmuQFw==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKcKaHQJ+uux1laZ6Xskzrj2RIbxeBOuH34+6V40dUEkxWAE6oSpL4xdXhoUW2P0aLqSFstDrhWSAACvHOg0N1ECAwEAAQ==
    host: mysql-prod

#redis配置
redis:
  ip: 120.25.65.104
  password: 123456
  port: 6379
  pool:
    maxIdle: 200
    maxTotal: 500
    testOnBorrow: true
    testOnReturn: true
    timeout: 3000