logging:
  level:
    com.vpclub.bait.busticket.query: debug

spring:
  rabbitmq:
    host: rabbit-dev

app:
  name: busticket
  project: bait
  role: query
  descriptions: '汽车票查询模块'
  cluster-name: bait
  datasource:
    name: bait_busticket
    username: vpman
    password: bkbvleNP/NySdTs4pdhIf6elabPUcVUS0Mwe+6qOhz0Xfgaqu/PWTxTAyJEcf+xJXKGjtaQB+aSxgpCXKpKcRQ==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJIMM/FfafGSwq0BHKFFXRJWH7tyMLewRin8IJleKRw+RPmdNP0rsfIJG02nhb0ABQBTun8W32KQa8ELwPuy8qsCAwEAAQ==
    host: mysql-dev-01.ek.io

#redis配置
redis:
  ip: 120.25.65.104
  password: 123456
  port: 6379
  pool:
    maxIdle: 200
    maxTotal: 500
    testOnBorrow: true
    testOnReturn: true
    timeout: 3000